//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public string ID { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChiCongTy { get; set; }
        public string SoDienThoai { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<double> VAT { get; set; }
    }
}
