//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDonNhap
    {
        public string MaCTHDNhap { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public string MaHoaDonNhap { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
    }
}
