//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDonBan
    {
        public string MaCTHDBan { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string MaCTKM { get; set; }
        public string MaHoaDonBan { get; set; }
    
        public virtual CTKM CTKM { get; set; }
        public string TenHangHoa { get; internal set; }
    }
}
