//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTKM()
        {
            this.CTHoaDonBan = new HashSet<CTHoaDonBan>();
            this.HoaDonBan = new HashSet<HoaDonBan>();
        }
    
        public string MaCTKM { get; set; }
        public string TenCTKM { get; set; }
        public Nullable<double> GiaTriKM { get; set; }
        public string LoaiKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonBan> CTHoaDonBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBan { get; set; }
    }
}
