//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.CTHoaDonNhap = new HashSet<CTHoaDonNhap>();
            this.Multimedia = new HashSet<Multimedia>();
        }
    
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string DonViTinh { get; set; }
        public string MaLoai { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonNhap> CTHoaDonNhap { get; set; }
        public virtual LoaiHangHoa LoaiHangHoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multimedia> Multimedia { get; set; }
    }
}
