//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_BANDIENTHOAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedia
    {
        public int ID { get; set; }
        public string Alt { get; set; }
        public string Url { get; set; }
        public string MaHangHoa { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
    }
}
